---
title: "Heating needs"
author: "Márton Kiss, MD"
format:
  docx:
    fig-width: 6
    fig-height: 4
    reference-doc: custom_ref_doc.docx
  html: default
editor: visual
prefer-html: true
toc: true
toc-depth: 2
execute:
  echo: false
  warning: false
---

```{r setup}
# Load packages, functions, and core data
source(here::here("inst", "function", "load_stuff.r"))

# Load analysis outputs (produced by iter4-iter6 pipeline)
if (file.exists(here::here("data", "cumulative_heat_models.Rdata"))) {
  load(here::here("data", "cumulative_heat_models.Rdata"))
}
if (file.exists(here::here("data", "cumulative_heat_predictions.Rdata"))) {
  load(here::here("data", "cumulative_heat_predictions.Rdata"))
}
if (file.exists(here::here("data", "decision_snapshot.Rdata"))) {
  load(here::here("data", "decision_snapshot.Rdata"))
}
```

```{r, child = here::here("inst", "Report_heatneed", "child1_preamble.qmd")}
```

\newpage

```{r, child = here::here("inst", "Report_heatneed", "child2.qmd")}
```

\newpage

# Remarks

### Other information regarding the document's compilation

```{r, comment='', results='asis'}
sessionInfo() %>% report::report() %>% cat()
```

### Time of compilation

```{r last_chunk, results='asis'}
Sys.time() %>% as.character() %>% cat()
```
